### ISSUE TITLE
Dataset download link in README is broken

### ISSUE THREAD

**Issue by Sakur00** [xiexinheng/NODE-ImgNet#1]
### Description
The dataset download link provided in the README file is no longer accessible.

### Expected Behavior
Please provide a new accessible link.

### Additional Context
The broken link is: [Google Drive](https://drive.google.com/file/d/120ZYtOgHpXJc3jfkdTFa0KzhsJQAEKiK/view?usp=share_link)

**Comment by fatemah-alh** [comment]
I also have the same problem.

**Comment by xiexinheng** [comment]
Sorry for the late reply. You can download the dataset from [The Waterloo Exploration Database (kedema.org)](https://kedema.org/project/exploration/index.html).
